module.exports = {
  content: ["./pages/**/*.{js,ts,jsx,tsx}", "./components/**/*.{js,ts,jsx,tsx}"],
  theme: {
    extend: {
      colors: {
        background: "#d7d8d8",
        primary: "#f37a28",
        secondary: "#4ba85a",
        other: "#be2026",
        background: "rgba(212,229,235,.3)",
        bg: "#104B92",
        text: "#EB7E23",
        title: "#FF5959",
        titleBlue: "#0c4159",
        textRed: "#87142b",
      },
      fontFamily: {
        title: ["DBHeaventRoundedBd"],
        body: ["DBHeaventRounded"],
        text: ["DBGinSiamX", "Georgia"],
        textBold: ["DBGinSiamXBd", "Georgia"],
        Poppins: ["Poppins"],
        Prompt: ["Prompt"],
        Kodchasan: ["Kodchasan-Regular"],
        k2d: ["K2D"],
        Mitr: ["Mitr"],
        DB: ["DBHelvethaicaX"],
        Athiti: ["Athiti"],
      },
      fontSize: {
        fsm: `clamp(0.83rem, 0.54vw + 0.62rem, 1rem)`,
        fbase: "clamp(1rem, 0.53vw + 0.9rem, 1.2rem)",
        fmd: `clamp(1.2rem, 0.64vw + 1.04rem, 1.44rem)`,
        flg: `clamp(1.44rem, 0.77vw + 1.25rem, 1.73rem)`,
        fxl: "clamp(1.73rem, 0.92vw + 1.5rem, 2.07rem)",
        f2xl: "clamp(2.07rem, 1.11vw + 1.8rem, 2.49rem)",
        f3xl: "clamp(2.49rem, 1.33vw + 2.16rem, 2.99rem)",
        f4xl: "clamp(3.5rem, 3vw , 11rem)",
        f5xl: "3rem",
        f6xl: "4rem",
        f7xl: "5rem",
        f27px: "27px",
      },
      animation: {
        youtubeSlide: "youtubeSlide 4s infinite alternate",
        "color-animation": "color-animation 5s linear infinite",
      },
      lineHeight: {
        "extra-loose": "2.5",
        'border-from-title': "4rem",
      },
    },
  },
  plugins: [require("@tailwindcss/line-clamp")],
}
